Dev
themilchenko/tehnopark_c_cpp_hw1 pull request #1
Opened 2022-03-17 21:25 UTC by themilchenko

2022-03-18 19:02 UTC, ITesserakt commented on include/Team.h
> +struct Team {
можно использовать 
```c
typedef struct {

} Team;
```

2022-03-18 19:02 UTC, ITesserakt commented on include/Team.h
> +typedef struct Team Team;
См. первое замечание

2022-03-18 19:03 UTC, ITesserakt commented on source/Team.c
> +    element->num_of_point_ = 0;
Зачем второй раз инициализировать поля структуры?

2022-03-18 19:04 UTC, ITesserakt commented on source/Team.c
> +    printf("=========================\n");
красиво, ставлю лайк

2022-03-18 19:06 UTC, ITesserakt commented on source/Team.c
> +    free(team);
free может кушать null

2022-03-18 19:07 UTC, ITesserakt commented on source/Team.c
> +char get_char(FILE *file) {
`file` may be null

2022-03-18 19:09 UTC, ITesserakt commented on source/Team.c
> +        int is_memory_allocate = 0;
замени int на bool

2022-03-18 19:10 UTC, ITesserakt commented on source/Team.c
> +            copy_str = (char *)malloc((string.capacity_ + 1) * sizeof(char));
`copy_str` may be null

2022-03-18 19:12 UTC, ITesserakt commented on source/Team.c
> +char *read_string(FILE *file) {
`file` may be null

2022-03-18 19:12 UTC, ITesserakt commented on source/Team.c
> +int read_integer(FILE *file) {
`file` may be null

2022-03-18 19:13 UTC, ITesserakt commented on source/Team.c
> +double read_double(FILE *file) {
`file` may be null

2022-03-18 19:15 UTC, ITesserakt commented on source/Team.c
> +void sort_teams(Team **competition, const int num_of_teams) {
`competition` may be null
`competition[i]` may be null

2022-03-18 19:20 UTC, ITesserakt commented on include/Team.h
> +void print_team(Team* team);
внутри функции ты структуру не меняешь, поэтому передавать надо через `const`

2022-03-18 19:22 UTC, ITesserakt requested changes
Тесты хорошие, документацию пишешь, молодец
Единственно, надо вынести функции для ввода (`read_*`) в отдельный файл

2022-03-19 13:32 UTC, ITesserakt commented on source/Team.c
> +        int is_memory_allocate = 0;
тип bool представляется true & false, а не 0 и 1

2022-05-07 15:54 UTC, leshiy1295 commented
@ITesserakt почему нет вердикта на портале, несмотря на многочисленные напоминания и просьбы?..

2022-05-07 16:47 UTC, leshiy1295 reviewed
В целом, неплохая работа, но не всё докрутили

2022-05-07 16:47 UTC, leshiy1295 commented on .github/workflows/ci.yml
> +      - run: make coverage
функция print_team не покрыта тестами
это связано с тем, что в ней захардкожен stdout в printf

2022-05-07 16:47 UTC, leshiy1295 commented on CMakeLists.txt
> +ENDIF ()
зачем это нужно?
WIN32/Apple/...
на CI всё на Linux всё равно запускается, требований к другим платформам никаких не было
да и вообще, зачем pthread в этой ДЗ?

2022-05-07 16:47 UTC, leshiy1295 commented on CMakeLists.txt
> +        -O0
почему не оставили только Wall Wextra и Wpedantic?

2022-05-07 16:47 UTC, leshiy1295 commented on linters/run.sh
> +
это взято из мастер-класса, но не добавлены scan-build/fbinfer

2022-05-07 16:47 UTC, leshiy1295 commented on include/Team.h
> +char* read_string();
почему это не в IO.h каком-нибудь, а в Team.h?

2022-05-07 16:47 UTC, leshiy1295 commented on include/Team.h
> +    int num_of_point_;
все поля публичные, почему они имеют постфикс _?

2022-05-07 16:47 UTC, leshiy1295 commented on include/Team.h
> +    int num_of_point_;
size_t

2022-05-07 16:47 UTC, leshiy1295 commented on include/Team.h
> +} Team;
зачем struct Team и Team одновременно?
обычно делают либо анонимную структуру, либо struct team и team_t

2022-05-07 16:47 UTC, leshiy1295 commented on include/Team.h
> +/*swap two teams for sorting*/
хороший код в документации не нуждается - он документирует себя сам...
ясно, что функция delete_team удаляет команду...

2022-05-07 16:47 UTC, leshiy1295 commented on source/Team.c
> +Team *create_team(int num, FILE *file) {
функция делает несколько вещей
- что-то читает
- что-то пишет
- инициализирует Team
- знает про num
это нарушает принцип SRP...

2022-05-07 16:47 UTC, leshiy1295 commented on source/Team.c
> +    if (*left && *right && *left != *right) {
вообще говоря, left или right могут быть NULL
и читаемее было бы проверить инверсию и сделать сразу return, а продолжить уже без отступа

2022-05-07 16:47 UTC, leshiy1295 commented on source/Team.c
> +void sort_teams(Team **competition, const int num_of_teams) {
size_t

2022-05-07 16:47 UTC, leshiy1295 commented on source/Team.c
> +                 (competition[j]->duration_ > competition[j + 1]->duration_))) {
сейчас критерий сортировки "захардкожен" внутри метода
нужно было его вынести наружу и передавать в виде отдельного аргумента - функции-компаратора...

2022-05-07 16:47 UTC, leshiy1295 commented on source/input.c
> +    } while (result != 1);
не требовалось вводить данные "до победного конца"
наоборот - если данные плохие, то достаточно было вернуть ошибку и корректно завершить программу

2022-05-07 16:47 UTC, leshiy1295 commented on source/input.c
> +char *read_string(FILE *file) {
сейчас эта функция делает две вещи:
- что-то читает
- реализует логику реаллокации
нужно было разбить на две...

2022-05-07 16:47 UTC, leshiy1295 commented on source/input.c
> +            string.capacity_ *= 2;
магическая константа

2022-05-07 16:47 UTC, leshiy1295 commented on source/input.c
> +                perror("Incorrect allocation of memory\n");
функция чтения не должна ничего печатать
она может вернуть ошибку, и уже внешняя функция, которая будет иметь доступ к stdout/stderr, его сможет как-то интерпретировать

2022-05-07 16:47 UTC, leshiy1295 commented on source/input.c
> +        if ((symbol >= '0' && symbol <= '9') && !is_after_point) {
стоило вынести в отдельную однострочную функцию

2022-05-07 16:47 UTC, leshiy1295 commented on source/main.c
> +    if (competition) {
сначала проверяйте некорректное условие и выходите...

2022-05-07 16:47 UTC, leshiy1295 commented on tests/test.cpp
> +    const char *test_case = "12\nElbrus\n12.22\n2\n";
```c
const char *test_case = "12\n"
                        "Elbrus\n"
                        "12.22\n"
                        "2\n"
```

2022-05-07 16:47 UTC, leshiy1295 commented on tests/test.cpp
> +    ASSERT_FALSE(strcmp(team->title_, "Elbrus"));
сейчас эти константы копипастятся между входом и выходом
стоило их вынести в отдельные переменные...
например, в C++20 появился std::format, который позволил бы удобно из них сделать входную строчку
(ну или можно было бы хотя бы std::string() собрать обычный и через c_str() получить const char * оттуда)

2022-05-07 16:47 UTC, leshiy1295 commented on tests/test.cpp
> +TEST(TeamTest, create_true_team) {
в C++ принято использовать camelCase

2022-05-07 16:47 UTC, leshiy1295 commented on tests/test.cpp
> +    ASSERT_EQ(second_team->num_of_point_, 3);
везде та же проблема
инициализация копируется
проверка копируется
данные копируются
стоило вынести в отдельные функции и избавиться от всей этой копипасты

2022-05-07 16:47 UTC, leshiy1295 commented on tests/test.cpp
> +    competition[3] = create_team(0, fourth_stream_case);
зачем здесь динамическое выделение памяти? Почему не обойтись обычным статическим массивом?
```c
Team *competitions[] = {
    create_team(0, "12\nTool\n12.22\n3\n"),
    create_team(0, "321\nSteel\n52.22\n6\n"),
    // ...
};
```

2022-05-07 16:47 UTC, leshiy1295 commented on tests/test.cpp
> +    ASSERT_EQ(competition[3]->num_of_point_, 3);
ну и, возможно, стоило сделать тест, который наивно через стандартный std::sort или как-то ещё реализовывал нужную логику, чтобы не нужно было прописывать всё явно вручную

2022-10-16 16:37 UTC, merged